name: SimpleCov

on:
  push:
    branches:
      - '**'

env:
  API: 0ab53c5238a1c2403b2ff0c4719f166eafc1978c47dc9af3cee5b08e18ab44ae
  LAT: 53.883945
  LNG: 27.541989

jobs:
  Code-coverage:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Build app
        uses: ./.github/actions/prebuild_app

      - name: Setup DB
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_HOST: localhost
        run: bin/rails db:setup

      - name: Test DB
        run: bundle exec rspec

      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: ./coverage
