name: Rspec

on:
  push:
    branches:
      - '**'

jobs:
  Rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2

      - name: Build app
        uses: ./.github/actions/prebuild_app

      - name: Setup DB
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_HOST: localhost
        run: bin/rails db:setup

      - name: Test DB
        run: bundle exec rspec
